import { render } from "@testing-library/react";
import type { Metadata } from "next";
import * as LayoutModule from "./layout";

// Mock next/font/google to avoid loading fonts in tests
jest.mock("next/font/google", () => ({
	Geist: jest.fn(() => ({ variable: "--font-geist-sans", subsets: ["latin"] })),
	Geist_Mono: jest.fn(() => ({
		variable: "--font-geist-mono",
		subsets: ["latin"],
	})),
}));

describe("layout.tsx", () => {
	it("should export correct metadata", () => {
		expect(LayoutModule.metadata).toEqual({
			title: "Create Next App",
			description: "Generated by create next app",
		});
	});

	it("should initialize Geist and Geist_Mono fonts", () => {
		// The mocks should have been called
		expect(require("next/font/google").Geist).toHaveBeenCalled();
		expect(require("next/font/google").Geist_Mono).toHaveBeenCalled();
	});
});
